name: Build 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        rustup default stable
        rustup update
    - name: Build
      run: cargo build
    - name: Build for no_std
      run: cargo build --no-default-features
    - name: Build for alloc
      run: cargo build --no-default-features --features alloc
    - name: Build with tokio adapters
      run: cargo build --features tokio
    - name: Build with async-std adapters (futures-rs)
      run: cargo build --features futures
    - name: Build with all adapters
      run: cargo build --features futures,tokio
    - name: Build documentation
      run: |
        cargo rustdoc --features futures,tokio
        echo "<!DOCTYPE html><html><head><script>window.location.replace(\"/core-futures-io/core_futures_io\");</script></head></html>" > target/doc/index.html
    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: target/doc