[package]
name = "erasure-traits"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.3.5", default-features = false }
core-futures-io = { path = "../core-futures-io" }

